sudo: false
language: python
matrix:
  # ugh. do I really have to list all tox stuff here??
  include:
    - python: 3.5
      env: DISTRIB="ubuntu" TOXENV='py35,flake8,mypy,pylint' COVERAGE="true"
    - python: 3.6
      env: DISTRIB="ubuntu" TOXENV='py36,flake8,mypy,pylint' COVERAGE="true"
    - python: 3.7
      dist: xenial # https://github.com/travis-ci/travis-ci/issues/9815
      env: DISTRIB="ubuntu" TOXENV='py37,flake8,mypy,pylint' COVERAGE="true"
install:
  - source tests/travis_install.sh
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  - tox
after_success:
  - if [[ "$COVERAGE" == "true" ]]; then coveralls || echo "failed"; fi
after_script:
  - travis-cleanup
cache:
  pip: true

